# Generated by Django 3.1.3 on 2021-04-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='passw',
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default=0, max_length=10, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grace',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
