# Generated by Django 3.1.3 on 2021-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210405_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('subj', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
